### ISSUE TITLE
System.AccessViolationException thrown when getting Vulkan graphics queue

### ISSUE THREAD

**Issue by opticfluorine** [opticfluorine/Vulkan2DExperiments#1]
In VulkanManager.createLogicalDevice(), the logical device is created successfully.  However, calling logicalDevice.GetQueue(graphicsQueueIndex, 0) throws a System.AccessViolationException.

Backtrace:
>  at Vulkan.Interop.NativeMethods.vkGetDeviceQueue(IntPtr device, UInt32 queueFamilyIndex, UInt32 queueIndex, IntPtr* pQueue)
>   at Vulkan.Device.GetQueue(UInt32 queueFamilyIndex, UInt32 queueIndex)
>   at Vulkan2DExperiments.VulkanManager.createLogicalDevice()

Not sure what is happening here.  Asked on StackOverflow at https://stackoverflow.com/questions/45268204/why-do-i-get-an-accessviolationexception-from-vulkansharp-when-trying-to-create.

**Comment by opticfluorine** [comment]
The issue lies in how VulkanManager.getGraphicsQueueIndex() identifies the graphics queue index.  The incorrect implementation used the queue count rather than the queue index.  This is fixed in commit f53feb17.
